### ISSUE TITLE
cudaFree(rawptr) failed with error an illegal memory access was encountered

### ISSUE THREAD

**Issue by d4l3k** [NVlabs/instant-ngp#133]
Hi, I'm trying to use this with a custom NeRF dataset but it crashes every time. Using the example inputs it works just fine but not on my dataset.

```
$ ./build/testbed --scene <path>/transforms.json
13:50:18 INFO     Loading NeRF dataset from
13:50:18 INFO       <path>/transforms.json
13:50:18 SUCCESS  Loaded 70 images of size 640x480 after 0s
13:50:18 INFO       cam_aabb=[min=[0.5,0.501615,0.5], max=[0.5,0.501615,0.5]]
13:50:18 INFO     Loading network config from: configs/nerf/base.json
13:50:18 INFO     GridEncoding:  Nmin=16 b=2.02126 F=2 T=2^19 L=16
13:50:18 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
13:50:18 INFO     Color model:   3--[SphericalHarmonics]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
13:50:18 INFO       total_encoding_params=14286560 total_network_params=10240
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:710 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:711 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:710 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:711 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:710 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:711 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:710 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:711 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:710 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:711 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:125 cudaFree(rawptr) failed with error an illegal memory access was encountered
13:50:18 ERROR    Uncaught exception: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:509 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
Could not free memory: /home/rice/Developer/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:439 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
```

I've tried switching to jpg as well as upscaling to 1080p. Is this aspect ratio related? Does it need to be exactly 1920x1080?

Here's the beginning of `transforms.json`. I've set transform_matrix to identity just to test the loading:

```
{
  "camera_angle_x": 0.7481849417937728,
  "camera_angle_y": 1.2193576119562444,
  "fl_x": 807.1375732421875,
  "fl_y": 807.1375732421875,
  "k1": 0.0578421,
  "k2": -0.0805099,
  "p1": -0.000980296,
  "p2": 0.00015575,
  "cx": 320,
  "cy": 240,
  "w": 640,
  "h": 480,
  "aabb_scale": 300,
  "frames": [
    {
      "file_path": "main_010.png",
      "sharpness": 31.72,
      "transform_matrix": [
        [
          1,
          0,
          0,
          0
        ],
        [
          0,
          1,
          0,
          0
        ],
        [
          0,
          0,
          1,
          0
        ],
        [
          0,
          0,
          0,
          1
        ]
      ]
    },
    {
      "file_path": "main_015.png",
      "sharpness": 31.72,
      "transform_matrix": [
        [
          1,
          0,
          0,
          0
        ],
        [
          0,
          1,
          0,
          0
        ],
        [
          0,
          0,
          1,
          0
        ],
        [
          0,
          0,
          0,
          1
        ]
      ]
    },
    ...
```

**Comment by Tom94** [comment]
Hi there, `aabb_scale` must be a power of two less or equal to 16. This is just a guess, but I hope changing it will fix the issue.

(If it does, we _really_ need to add meaningful error output rather than letting the rest of the program fall flat on its face.)

**Comment by d4l3k** [comment]
Setting it to 4 did the trick :) Thanks for the help!

**Comment by wangjksjtu** [comment]
@Tom94, @mmalex  In my unbounded scene, it seems that larger `aabb_scale` leads to better results (especially for the sky). It seems that `aabb_scale` does not support a power of two larger 16. Are there any reasons for this? In general, do you have more thoughts on how to model the background? I noticed that there is a learnable parameter for env map, would this be beneficial?

Thanks for your great help!

**Comment by Tom94** [comment]
Hi there, while I implemented rudimentary learned envmaps, I wouldn't say they're in a state in which they're immediately useable -- they will need some form of multi-scale training to work well.

The reason for `aabb_scale` is a somewhat arbitrary compile-time limitation on the number of cascades. If you increase the compile-time value of `NERF_CASCADES()`, it'll allow larger `aabb_scale` to be used. This is the path of least resistance I'd recommend using for now.
